version: '3.9'

services:
  workspace:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: magpie-developer-challenge
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - "5435:5432"

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
      - redis

volumes:
  redis:
  redis-config:
  postgres:

networks:
  redis-network:
    driver: bridge